---
title: "Exercise 3"
author: "Brandon Gulley"
date: "`r Sys.Date()`"
output: 
  html_document:
  fig_caption: yes
---

``` {r setup, echo=FALSE, warning = FALSE, message = FALSE}

library(tidyverse)
library(gtsummary)
library(gt)
library(palmerpenguins)
library(flextable)
library(readxl)
library(knitr)
library(dplyr)

```

``` {r data, echo=FALSE, include=TRUE}

mammals <- read_xlsx("smallmammal.xlsx")

mammals_PEMA <- mammals %>%
  filter(species == "PEMA")

```

``` {r ttest, warning=FALSE, message=FALSE, echo=FALSE, include=TRUE}

table_mammals1 <- mammals_PEMA %>%
  select(sex, animal_mass_g, body_length_mm, hindfoot_length_mm, ear_length_mm, tail_length_mm) %>% 
  tbl_summary(
    by = sex,
    missing = "no",
    digits = all_continuous() ~ 1,
    label = list(
      animal_mass_g ~ "Mass (g)",
      body_length_mm ~ "Body Length (mm)",
      hindfoot_length_mm ~ "Hindfoot Length (mm)",
      ear_length_mm ~ "Ear Length (mm)",
      tail_length_mm ~ "Tail Length (mm)"
    ),
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{n}") 
  ) %>% 
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>% 
  modify_caption("Table 1. *Peromyscus maniculatus* Morphological Characteristics") %>%
  modify_header(
    update = list(
      label ~ '',
      stat_1 ~ '**Female**', 
      stat_2 ~ '**Male**',
      p.value ~ '**P-value**')
  )
                
table_mammals1

```

``` {r ttest plot, echo=FALSE, include=TRUE, fig.align='center', fig.cap = "Figure 1: Bar chart comparing mean body mass in g between males and females of the North American deer mouse."}

mammals_PEMA2 <- mammals_PEMA %>% 
group_by(sex) %>% 
  summarise(mean_mass = mean(animal_mass_g), sd_mass = sd(animal_mass_g), count = n(), se_mass = (sd_mass/(sqrt(count))))

ggplot(mammals_PEMA2, aes(x = sex, y = mean_mass, width = .25, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Sex") +
  ylab("Mean Mass (g)") +
  geom_errorbar(aes(ymin = mean_mass - se_mass, ymax = mean_mass + se_mass), width = .1) 

```
``` {r ANOVA data, echo=FALSE, include=FALSE}

mammals_ANOVA <- filter(mammals, species %in% c("PELE", "ORPA", "PEMA"))

```

``` {r ANOVA, echo=FALSE, warning=FALSE, message=FALSE, include=TRUE}

table_mammals2 <- mammals_ANOVA %>%
  select(species, sex, hindfoot_length_mm, tail_length_mm) %>%
  tbl_summary(
    by = species,
    missing = "no",
    digits = all_continuous() ~ 1,
    label = list(
      hindfoot_length_mm ~ "Hindfoot Length (mm)",
      tail_length_mm ~ "Tail Length (mm)",
      sex ~ "Sex"
    ),
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{n}")
  ) %>% 
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>% 
  modify_caption("Table 2. Small mammal hindfoot and tail length characteristics") %>%
  modify_footnote(everything() ~ NA) %>%
  modify_header(
    update = list(
      label ~ '',
      stat_1 ~ '**P. leucopus**',
      stat_2 ~ '**O. palustris**',
      stat_3 ~ '**P. maniculatus**',
      p.value ~ '**P-value**'
    )
  )

                
table_mammals2

```

``` {r ANOVA plot, echo=FALSE, include=TRUE, fig.align='center', fig.cap = "Figure 2: Boxplot comparing hindfoot length between male and female in three different species including the North American deer mouse (PEMA), white-footed mouse (PELE), and marsh rat (ORPA)."}

anova_plot <- ggplot(mammals_ANOVA, aes(x = species, y = hindfoot_length_mm, color = sex)) +
  geom_boxplot() +
  xlab("Species") +
  ylab("Hindfoot Length (mm)")

anova_plot

```

``` {r ANCOVA data, echo=FALSE, include=FALSE}

mammals_PEMA <- mammals %>%
  filter(species == "PEMA")

```

``` {r ANCOVA, echo=FALSE, warning=FALSE, message=FALSE, include=TRUE}

table_mammals3 <- mammals_PEMA%>% 
  select(body_length_mm, hindfoot_length_mm, ear_length_mm, tail_length_mm, sex)%>%
  tbl_summary(by=sex, 
              digits = all_continuous() ~ 1,
              include=c(body_length_mm, hindfoot_length_mm, ear_length_mm),
              )%>%
  add_difference(adj.vars=c(tail_length_mm)) 

table_mammals3

```

``` {r ANCOVA model, echo=FALSE, include=FALSE}

model_1 <- lm(body_length_mm ~ tail_length_mm + sex, data = mammals_PEMA)

```

``` {r ANCOVA plot, echo=FALSE, include=TRUE, fig.align='center', fig.cap = "Figure 3: Linear regression comparing tail and body length in mm between males and females of the North American deer mouse."}

ggplot(model_1) +
  geom_point(aes(x = tail_length_mm, y = body_length_mm, color = sex)) +
  geom_line(aes(x = tail_length_mm, y = .fitted, color = sex)) +
  geom_vline(xintercept=mean(mammals_PEMA$tail_length_mm), linetype='dashed', color='red') +
  xlab("Tail Length (mm)") +
  ylab("Body Length (mm)") 

```